# QnA Question and Action

## Welfare

### I am feeling burned out
- Contact Tim if you feel unable to cope with the workload and we will work out a solution, which may include:
  - Delegate your work to your committee members
  - Support or direct involvement of the national commitee members to help with local tasks 

## Publicity

### Our spoke has a event that is open to all, how can we publicize it
- Post it on your local spoke's social media pages if there is any
- Encourage your local spoke's committee members to share the post
- Send the link of the event to [National MedTech Foundation's Facebook page](https://www.facebook.com/medtechfoundation/). The publicity team will publicize it via all channels that we have

## Ideas

### I have an idea to be discussed with everyone
- Add it to the running agenda [here](https://docs.google.com/document/d/1lLqygjAAKhP70giSbeTDaq9fs3gaoBBxEmxwHwXx7HQ/edit)

### I have an idea that I want to implement
- Post it in the #general channel and the idea may take off from the discussion there!
- If it is an idea that requires any commitee members' actions (i.e. contacting industry partners), send a DM to them on slack



## Finance 

### What are the sources for funding
Associate with your local or closest MIC, 
Apply for funding from your university student union, 
Reach out to external organisations for sponsorship package

### Need help for approaching sponsors 
- ask Jye on slack or at finance@medtechfoundation.org

### Financial support from national
- currently unavailable, but we are working on it! 

## Communication

### I have messaged this person in MTF but there is no reply
- Check national calendar to see if they are available
- Send them an email 
- Use emergency contact 
- Contact Tim as he may know someone who can do the same job




